"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Maker = exports.ParamType = exports.Param = exports.Plugins = exports.Errors = exports.Context = exports.Group = exports.Core = exports.Event = exports.Command = exports.Fold = exports.Erine = exports.Bucket = void 0;
const tslib_1 = require("tslib");
const Bot_1 = require("./classes/Bot");
Object.defineProperty(exports, "Erine", { enumerable: true, get: function () { return Bot_1.Erine; } });
const CommandMacro_1 = require("./decorators/CommandMacro");
Object.defineProperty(exports, "Command", { enumerable: true, get: function () { return CommandMacro_1.Command; } });
const GroupMacro_1 = require("./decorators/GroupMacro");
Object.defineProperty(exports, "Group", { enumerable: true, get: function () { return GroupMacro_1.Group; } });
const EventMacro_1 = require("./decorators/EventMacro");
Object.defineProperty(exports, "Event", { enumerable: true, get: function () { return EventMacro_1.Event; } });
const Core_1 = require("./classes/Core");
Object.defineProperty(exports, "Core", { enumerable: true, get: function () { return Core_1.Core; } });
const Context_1 = require("./classes/Context");
Object.defineProperty(exports, "Context", { enumerable: true, get: function () { return Context_1.Context; } });
const Fold_1 = require("./classes/Fold");
Object.defineProperty(exports, "Fold", { enumerable: true, get: function () { return Fold_1.Fold; } });
const Maker_1 = require("./classes/Maker");
Object.defineProperty(exports, "Maker", { enumerable: true, get: function () { return Maker_1.Maker; } });
const ParamsMacro_1 = require("./decorators/ParamsMacro");
Object.defineProperty(exports, "Param", { enumerable: true, get: function () { return ParamsMacro_1.Param; } });
Object.defineProperty(exports, "ParamType", { enumerable: true, get: function () { return ParamsMacro_1.ParamType; } });
const Errors = tslib_1.__importStar(require("./classes/Errors"));
exports.Errors = Errors;
const Plugins = tslib_1.__importStar(require("./decorators/PluginsMacro"));
exports.Plugins = Plugins;
var Bucket;
(function (Bucket) {
    Bucket["Member"] = "MEMBER";
    Bucket["User"] = "USER";
    Bucket["Guild"] = "GUILD";
    Bucket["Channel"] = "CHANNEL";
})(Bucket = exports.Bucket || (exports.Bucket = {}));
tslib_1.__exportStar(require("oceanic.js"), exports);
exports.default = { Erine: Bot_1.Erine, Fold: Fold_1.Fold, Command: CommandMacro_1.Command, Event: EventMacro_1.Event, Core: Core_1.Core, Group: GroupMacro_1.Group, Context: Context_1.Context, Errors, Plugins, Maker: Maker_1.Maker };
